### ISSUE TITLE
Catch "rate limit" error with wrong API key on login

### ISSUE THREAD

**Issue by DasSkelett** [nbuchwitz/nc_dnsapi#5]
As requested in https://github.com/ansible-collections/community.general/pull/2590

When executing through ansible, I got the following exception:
```
Traceback (most recent call last):
  File "/tmp/ansible_netcup_dns_payload_660r169c/ansible_netcup_dns_payload.zip/ansible_collections/community/general/plugins/modules/netcup_dns.py", line 220, in main
  File "/home/user/.local/lib/python3.9/site-packages/nc_dnsapi/__init__.py", line 192, in __init__
    self.login()
File "/home/user/.local/lib/python3.9/site-packages/nc_dnsapi/__init__.py", line 107, in login
    data = self.request("login", params={"apipassword": self.__api_password})
  File "/home/user/.local/lib/python3.9/site-packages/nc_dnsapi/__init__.py", line 98, in request
    raise Exception("{} ({})".format(data['longmessage'], data['statuscode']))
Exception: More than 180 requests per minute. Please wait and retry later. Please contact our customer service to find out if the limitation of requests can be increased. (4013)
```
I can reproduce the same by directly invoking the nc_dnsapi Python module.

As it turned out, this was caused by an incorrect API key (it had a `\n` suffix), and not a big amount of requests that would exceed the API rate limit.
To reproduce, pass an incorrect API key (but correct customer ID, API password doesn't matter as it's validated afterwards) to the `Client` constructor.

It looks like the netcup API returns an incorrect  / misleading error message there. It would make sense to catch this error and, when it happens during login, give the user a better message, pointing to the possibility of an incorrect API key.

**Comment by nbuchwitz** [comment]
@DasSkelett could you please check if the hint in #7 would be enough?
